[versions]
yutori = "83465ece99a41e761631baeebf86af7d70bd51da"
agp = "8.6.1"

[libraries]
yutori = { module = "cn.yurin.yutori:yutori", version.ref = "yutori" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }