[versions]
yutori = "efe81ad36eff647d299acddff8ea24f1f31f8a5c"
agp = "8.6.1"

[libraries]
yutori = { module = "cn.yurin.yutori:yutori", version.ref = "yutori" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }