name: Publish package to GitHub Packages
on:
  push:
    branches: [ master ]
jobs:
  publish-kotlin-multiplatform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Publish kotlinMultiplatform package
        run: ./gradlew publishKotlinMultiplatformPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.sha }}
  publish-jvm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Publish jvm package
        run: ./gradlew publishJvmPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.sha }}
  publish-android-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Publish androidDebug package
        run: ./gradlew publishAndroidDebugPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.sha }}
  publish-android-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Publish androidRelease package
        run: ./gradlew publishAndroidReleasePublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.sha }}